### ISSUE TITLE
integration with codeclimate.com?

### ISSUE THREAD

**Issue by aspiers** [filib/codeclimate-shellcheck#22]
This looks great!  Please can you share when it will be available for use via codeclimate.com?  Thanks.

**Comment by filib** [comment]
Hey @aspiers! For some reason, I didn't get a notification about this issue. Sorry for the late reply.

I'm not directly affiliated with CodeClimate so I can't answer that one. @mrb?

**Comment by mrb** [comment]
@filib @aspiers Oops I missed this one too! We're still working on making the engine CC compliant but that should be done soon! After that we'll try it out on a few repos and then ship it for GA. Stay tuned to the repo for more info!

**Comment by mrb** [comment]
@aspiers If you're interested in testing this out, shoot me an email mrb@codeclimate.com

**Comment by aspiers** [comment]
Hi - yes I am very interested although unfortunately won't have any free
time for it until mid Feb. Is that too late? Thanks!

On 19 Jan 2016 22:47, "Michael Bernstein" <notifications@github.com> wrote:
>
> @aspiers If you're interested in testing this out, shoot me an email
mrb@codeclimate.com

**Comment by filib** [comment]
@aspiers this engine is now generally available on Code Climate. More details at https://codeclimate.com/changelog/56e0b52837af5a008e000ba4

Let us know if you have any feedback!

**Comment by aspiers** [comment]
That's fantastic news, thanks so much and yes we will try this out for sure and give feedback if we find anything which we think could be improved!
