### ISSUE TITLE
Transform ShellCheck output to Issue type

### ISSUE THREAD

**Issue by filib** [filib/codeclimate-shellcheck#3]
Follows on from https://github.com/filib/codeclimate-shellcheck/issues/2.

**Comment by filib** [comment]
I'm going to tackle this one on the train today. It looks like all we have to do is marshall between `CheckResult` and our `Issue` type.

**Comment by filib** [comment]
@mrb earlier this morning I was wondering if it was worth going to all the effort of interfacing with ShellCheck as a library. 

We could always just shell out to the binary, use its JSON output and transform that into our issue type. The advantage is that we'd get something up and running quickly but the disadvantage is that we wouldn't know at compile time if the ShellCheck interface has changed. 

I'm leaning towards the compile time safety but wondered if you think I'm just being daft. What do you think?

**Comment by mrb** [comment]
@filib I think it's totally fine to shell out to it - easy and fast wins. Keep in mind we want to be able to pass a config to shellcheck, but that should also be easy with this approach.
