### ISSUE TITLE
Update engine?

### ISSUE THREAD

**Issue by mrb** [filib/codeclimate-shellcheck#57]
Hey @filib - should we release a new version of the engine?

**Comment by filib** [comment]
Hey - I reckon we should!

**Comment by filib** [comment]
@mrb how does that happen? Do you have an internal process for this?

**Comment by mrb** [comment]
@filib We do. You can either ping me in slack or fill out the engine update form.

**Comment by filib** [comment]
@mrb will you close this issue once it's live?

**Comment by filib** [comment]
Submitted the engine update form. Gonna mark as closed ✌️️
