### ISSUE TITLE
Skipping .bash files

### ISSUE THREAD

**Issue by abbyarmada** [filib/codeclimate-shellcheck#58]
Hi @filib. Abby here from Code Climate's support team.

A user reached out to us saying that shellcheck in Code Climate skipped their `blip.bash` file  (in https://github.com/neechbear/blip/)  We tested it on our end, and shellcheck also skips this file. If we change it to `blip.bash.sh` it shows issues in spellcheck. 

Running shellcheck manually (v 0.3.3)  on the command line against https://raw.githubusercontent.com/neechbear/blip/master/blip.bash shows some shellcheck warnings.

Is skipping `.bash` files intended? 

Any insight on this would be great! Thanks.

**Comment by neechbear** [comment]
If there's a configuration option in `.codeclimate.yaml` that I can add to indicate which files should be examined, that would be fantastic.

**Comment by filib** [comment]
@abbyarmada It shouldn't be skipping that file. I requested an update via the webform that fixed this in the last month. Has your team actioned this?

**Comment by filib** [comment]
https://github.com/filib/codeclimate-shellcheck/issues/57

**Comment by filib** [comment]
https://github.com/filib/codeclimate-shellcheck/pull/54

**Comment by filib** [comment]
@neechbear unfortunately there isn't a configuration available because the engine will first validate that the shell script can be analysed before submitting for analysis. Previously the behaviour was that it'd check if the extension was .sh or check the shebang for a valid interpreter. This was improved recently but I suspect that it hasn't yet been deployed.

**Comment by abbyarmada** [comment]
@filib 🤔 I guess not! I'll touch base with our engineering team. Sorry about that!

**Comment by filib** [comment]
@abbyarmada no worries! Hopefully @neechbear will be able to analyse that .bash file soon.

**Comment by abbyarmada** [comment]
@filib Good news! I did some digging with someone on our engineering team, and we were able to ship the update to shellcheck over here.

(We also updated that form so it goes to the right person. Hurrah!)

@neechbear -- you should be able to analyze that `blip.bash` file now. Thanks so much for your patience.

**Comment by filib** [comment]
It shouldn't be skipping that file. I requested an update via the webform that fixed this in the last month. Has your team actioned this?

**Comment by filib** [comment]
@abbyarmada that's great news. I'll close once I hear it's working for @neechbear.

**Comment by filib** [comment]
I just looked on https://codeclimate.com/github/neechbear/blip/issues and it looks like it's now analysing .bash files.
