### ISSUE TITLE
Update shellcheck and engine please

### ISSUE THREAD

**Issue by sysadmiral** [filib/codeclimate-shellcheck#59]
Hi,

the docs suggest the shellcheck version is out of date which would require an engine update.

Would this be possible?

Cheers,

Amo

**Comment by filib** [comment]
I'll try and update this at the weekend.

**Comment by filib** [comment]
I haven't forgotten about this but if you have some free time, feel free to submit a patch. Otherwise I'll do it when I'm back from vacation.

**Comment by filib** [comment]
@abbyarmada I've updated things at this end. Are you able to test on the CodeClimate end?

**Comment by filib** [comment]
@sysadmiral I've been told this has been deployed to production. Feel free to give it a spin.
